### ISSUE TITLE
annotations conflicts with bg_color

### ISSUE THREAD

**Issue by yslan** [Alpine-DAV/ascent#1203] opened 2023-10-13 08:59 UTC
I want to turn off legend, remove the bounding box, and set white background color. 

However, the setting below seems to overwrite the `bg_color`
- set 1: resulting black background
```
      renders:
        r1:
          world_annotations: false
          screen_annotations: false
          bg_color: [1.0, 1.0, 1.0]
          fg_color: [0.0, 0.0, 0.0]
```

Interestingly, if I only turn off one of the annotation, the `bg_color` will be correct, but settings both annotations off won't work.

- set 2: resulting white background
```
      renders:
        r1:
          world_annotations: false
          bg_color: [1.0, 1.0, 1.0]
          fg_color: [0.0, 0.0, 0.0]
```

- set 3: resulting white background
```
      renders:
        r1:
          screen_annotations: false
          bg_color: [1.0, 1.0, 1.0]
          fg_color: [0.0, 0.0, 0.0]
```

Speaking of background, is there anyway to get transparent background?

**Comment by nicolemarsaglia** [comment] 2023-10-13 23:05
That is some interesting and unintentional behavior. Thanks for brining this to our attention! 

@cyrush can correct me if I'm wrong, but I do not believe we support transparent backgrounds currently. But it is something we can look into!

**Comment by nicolemarsaglia** [comment] 2023-10-13 23:37
I believe I have a fix in PR #1204

**Comment by nicolemarsaglia** [comment] 2023-10-18 03:52
Merged!

**Comment by nicolemarsaglia** [comment] 2023-10-24 18:09
I'm going to open a separate issue to track your transparency request. Feel free to close this issue unless there is something else or the problem isn't fixed for you.

**Closed as completed** 2023-10-24 18:22 UTC
